### PR TITLE
Fix issue with ScalateUrlGeneratorSupport and reverse-routes.

### LINKED ISSUE #761: Error when more than one servlet extends ScalateUrlGeneratorSupport
Given two (or more) servlets that:
* extend [ScalateUrlGeneratorSupport](https://github.com/scalatra/scalatra/blob/2.6.x/scalate/src/main/scala/org/scalatra/scalate/ScalateUrlGeneratorSupport.scala)
and
* has a [reverse-route variable](http://scalatra.org/guides/2.6/http/reverse-routes.html) assigned

When a request is made that results in a scalate template being rendered,

Then the following exception is raied
```
org.fusesource.scalate.NoValueSetException: The value for 'twoBaz' was not set
 at org.fusesource.scalate.RenderContext.$anonfun$attribute$1(RenderContext.scala:160)
 at scala.Option.getOrElse(Option.scala:121)
 at org.fusesource.scalate.RenderContext.attributeOrElse(RenderContext.scala:167)
 at org.fusesource.scalate.RenderContext.attributeOrElse$(RenderContext.scala:165)
 at org.fusesource.scalate.DefaultRenderContext.attributeOrElse(DefaultRenderContext.scala:30)
 at org.fusesource.scalate.RenderContext.attribute(RenderContext.scala:160)
 at org.fusesource.scalate.RenderContext.attribute$(RenderContext.scala:159)
 at org.fusesource.scalate.DefaultRenderContext.attribute(DefaultRenderContext.scala:30)
 at views.$_scalate_$simple_ssp$.$_scalate_$render(simple.ssp.scala:20)
 at views.$_scalate_$simple_ssp.render(simple.ssp.scala:36)
 at org.fusesource.scalate.DefaultRenderContext.capture(DefaultRenderContext.scala:93)
 at org.fusesource.scalate.layout.DefaultLayoutStrategy.layout(DefaultLayoutStrategy.scala:45)
 at org.fusesource.scalate.TemplateEngine.$anonfun$layout$2(TemplateEngine.scala:577)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 at org.fusesource.scalate.RenderContext.withUri(RenderContext.scala:444)
 at org.fusesource.scalate.RenderContext.withUri$(RenderContext.scala:436)
 at org.fusesource.scalate.DefaultRenderContext.withUri(DefaultRenderContext.scala:30)
 at org.fusesource.scalate.TemplateEngine.$anonfun$layout$1(TemplateEngine.scala:577)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 at org.fusesource.scalate.RenderContext$.using(RenderContext.scala:49)
 at org.fusesource.scalate.TemplateEngine.layout(TemplateEngine.scala:573)
 at org.fusesource.scalate.TemplateEngine.layout(TemplateEngine.scala:566)
 at org.fusesource.scalate.TemplateEngine.layout(TemplateEngine.scala:634)
 at org.scalatra.scalate.ScalateSupport.layoutTemplateAs(ScalateSupport.scala:246)
 at org.scalatra.scalate.ScalateSupport.layoutTemplateAs$(ScalateSupport.scala:236)
 at com.example.app.ServletOne.layoutTemplateAs(ServletOne.scala:6)
 at org.scalatra.scalate.ScalateSupport.ssp(ScalateSupport.scala:219)
 at org.scalatra.scalate.ScalateSupport.ssp$(ScalateSupport.scala:218)
 at com.example.app.ServletOne.ssp(ServletOne.scala:6)
 at com.example.app.ServletOne.$anonfun$oneFoo$1(ServletOne.scala:10)
 at org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:280)
 at org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:274)
 at org.scalatra.ScalatraBase.withRouteMultiParams(ScalatraBase.scala:351)
 at org.scalatra.ScalatraBase.withRouteMultiParams$(ScalatraBase.scala:347)
 at com.example.app.ServletOne.withRouteMultiParams(ServletOne.scala:6)
 at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:273)
 at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:272)
 at com.example.app.ServletOne.invoke(ServletOne.scala:6)
 --- snip ---
```

This error is re-raised as scalatra attempts to render the default error page, preventing the error page from being displayed.

I've seen this behaviour with scalatra 2.5, 2.6 and 2.7 but have not tested older versions.

### PR DESCRIPTION
**Pull request by j1mr10rd4n**
This PR fixes #761.

When reverse routes are reflected on and saved to the scalate context, they now include information about the servlet in which they were declared.

Note that in order to avoid collisions, the variable names for reverse routes should be unique across all servlets. A warning to this effect was added to the User Guide in [scalatra-website PR 174](https://github.com/scalatra/scalatra-website/pull/174)

### CODE REVIEW

**Comment by j1mr10rd4n** [comment]
Looks like the scala-2.12 builds have timed out - I saw this a couple of times locally also - is this a known issue since the move to sbt-1.0 ?

**Comment by takezoe** [comment]
Travis build is unstable recently... I will rerun failed builds.

File: scalate/src/main/scala/org/scalatra/scalate/ScalateUrlGeneratorSupport.scala [hunk 1]
```diff
@@ -18,16 +18,33 @@ trait ScalateUrlGeneratorSupport extends ScalateSupport {
...
+        val pathReplacingFn = { req: HttpServletRequest =>
+          route.contextPath(req)
+            .replaceFirst(
+              pathForCurrentRequest,
+              pathForServletContainingRoute.replaceFirst("/\\*", ""))
+        }
+        val routeWithOwnServletPath = route.copy(contextPath = pathReplacingFn)
+        context.attributes.update(name, routeWithOwnServletPath)
+      }
+    }
```
Comment (takezoe) [inline scalate/src/main/scala/org/scalatra/scalate/ScalateUrlGeneratorSupport.scala]: Isn't it possible to use methods in `UrlGenerator` to assemble url?

File: core/src/main/scala/org/scalatra/servlet/RichServletContext.scala [hunk 2]
```diff
@@ -222,5 +222,17 @@ case class RichServletContext(sc: ServletContext) extends AttributesMap {
...
+
+  def addGeneratedUrls(servletClassName: String, routes: Map[String, Route]) = {
+    sc.setAttribute(generatedUrlsKey, generatedUrls + (servletClassName -> routes))
+  }
+
+  def generatedUrls = {
+    Option(sc.getAttribute(generatedUrlsKey))
+      .getOrElse(Map.empty[String, Map[String, Route]])
+      .asInstanceOf[Map[String, Map[String, Route]]]
+  }
```
Comment (takezoe) [inline core/src/main/scala/org/scalatra/servlet/RichServletContext.scala]: I think that these code should be in `ScalateUrlGeneratorSupport` side because `RichServletContext` shouldn't know something about `ScalateUrlGeneratorSupport`.

File: core/src/main/scala/org/scalatra/servlet/RichServletContext.scala [hunk 3]
```diff
@@ -222,5 +222,17 @@ case class RichServletContext(sc: ServletContext) extends AttributesMap {
 
   def contextPath: String = sc.getContextPath
 
+  val generatedUrlsKey = "org.scalatra.scalate.generatedUrls"
+
+  def addGeneratedUrls(servletClassName: String, routes: Map[String, Route]) = {
+    sc.setAttribute(generatedUrlsKey, generatedUrls + (servletClassName -> routes))
```
Comment (takezoe) [inline core/src/main/scala/org/scalatra/servlet/RichServletContext.scala]: It would be nice if it warns name collision as you mentioned in the gitter room.

Comment (j1mr10rd4n) [reply core/src/main/scala/org/scalatra/servlet/RichServletContext.scala]: Ok, I can add in a Logger instance and a warning.

File: core/src/main/scala/org/scalatra/servlet/RichServletContext.scala (hunk 2 above)
Comment (j1mr10rd4n) [reply core/src/main/scala/org/scalatra/servlet/RichServletContext.scala]: Good point!

File: scalate/src/main/scala/org/scalatra/scalate/ScalateUrlGeneratorSupport.scala (hunk 1 above)
Comment (j1mr10rd4n) [reply scalate/src/main/scala/org/scalatra/scalate/ScalateUrlGeneratorSupport.scala]: [UrlGenerator](https://github.com/scalatra/scalatra/blob/v2.6.2/core/src/main/scala/org/scalatra/UrlGenerator.scala) does assemble urls from [Routes](https://github.com/scalatra/scalatra/blob/v2.6.2/core/src/main/scala/org/scalatra/Route.scala) - the intent of the fix made to [ScalateUrlGeneratorSupport](https://github.com/scalatra/scalatra/blob/v2.6.2/scalate/src/main/scala/org/scalatra/scalate/ScalateUrlGeneratorSupport.scala) is to save Routes with the correct context paths to generate the urls from.

**Comment by j1mr10rd4n** [comment]
Hi @takezoe - I've done a bit of refactoring and moved all changes in to [ScalateUrlGeneratorSupport](https://github.com/scalatra/scalatra/blob/v2.6.2/scalate/src/main/scala/org/scalatra/scalate/ScalateUrlGeneratorSupport.scala) and added a log message at warning level if duplicate reverse routes are found.

**Comment by takezoe** [comment]
@j1mr10rd4n By the way, reverse routing seems to be available only within a controller, originally because it requires a method reference.
http://scalatra.org//guides/2.6/http/reverse-routes.html

Unlike it, this pull request makes possible to get routes of all controllers. This difference might confuse users. Sorry we had to discuss about this difference in the first place but I noticed it after merging this pull request.

I would like to hear your opinion.
